### ISSUE TITLE
Icon Request - Merkuro Calendar

### ISSUE THREAD

**Issue by mercifulboss** [SylEleuth/gruvbox-plus-icon-pack#43]
Can you please add a icon for Merkuro Calenar (as well as mail and contacts)?

![image](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/90151527/2db182a9-a571-4fcd-a3f9-bb34883ff844)

This is an official KDE app currently under development

https://github.com/KDE/merkuro

https://apps.kde.org/merkuro.calendar/

**Comment by SylEleuth** [comment]
https://github.com/SylEleuth/gruvbox-plus-icon-pack/commit/24f980c0ccd342039007fce1a9a06bc6dae654b3

Links provided by You do not have icons for Merkuro apps (calendar, contact, mail), only for Kalendar, which is going to be replaced by those apps. Unfortunately I cannot test it at the moment. Can You do that and tell me if they display properly?

**Comment by mercifulboss** [comment]
Hello, thanks for doing this so rapidly.

It seems to work, but for some reason the color is not maintained in the taskbar with some icons being white and others yellow:

![image](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/90151527/172ecac3-14d9-4044-821b-258a0c3243be)

It seems the larger icons work as well

![merkuro](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/90151527/81b9488e-6245-415d-a855-657803bfe77f)

**Comment by SylEleuth** [comment]
That will be hard to find a culprit. First thing I can think of is the old formatting. Let's test it on a new calendar icon. I've just pushed it to repo. It's only one icon but it will give me so direction where to go with that. Could You pull it and test it?

**Comment by mercifulboss** [comment]
It worked. I had to switch to another theme and then switch back and it updated:

![image](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/90151527/5ed42d97-6da9-4fc5-b00f-f64c6ef2661c)


The 'H' is the icon for Optimus Manager Hybrid mode (to select between using either dedicated GPU, both GPU and integrated graphs or just integrated graphics):

![Gruvbox theme](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/90151527/4a52e20a-8118-44b2-8cd7-2654e0dd3d27)

**Comment by SylEleuth** [comment]
So I believe I found and corrected every each icon on Your task bar. Especially "bulb" icon, which is a new one (and terminal, and wifi). I'm currently working on "apps" folder and some of those changes are temporary until I finish and merge them properly so sizes might be off a little bit. And I can't test "Optimus manager" because I'm on the AMD but it should be fine now.
Let me know how it looks and I will make additional changes if necessary.

**Comment by mercifulboss** [comment]
Thank you for taking the time!

It looks great!😍  

For some reason however, Firefox and optimus manager do not update properly:

![image](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/90151527/c4fc45c9-0487-4476-921a-4f738219b436)

Also, it seems that when new apps are opened they still follow the old theme. Not sure what I am doing wrong:

![image](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/90151527/d366a31f-f9c2-4074-9b78-0a6d4b6549c7)

Those are the libre-office and spectacle apps

In addition I noticed that other entries in the application menu are white. Not sure if I am doing something wrong or its supposed to be that way but I thought i'd point it out:
![gruvbox icons plus application menu](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/90151527/f09d3aad-bd72-4a7f-81d5-8b5a087fb806)

**Comment by SylEleuth** [comment]
1. Saying that I "corrected every each icon" was of course wrong because I forgot to add `firefox` and somehow I missed `spectacle` (`screenshot` icon). I've just added them.
2. I've also made some mistakes with `hybrid` icon. Please tell me how it looks now.
3. You are not doing anything wrong. Apps icons are not formatted properly and require a lot of work (because there are thousands of them). As I said previously I'm on it right now but there are other icons in my queue. On the request I will add missing icons or modify broken ones, but at the moment I can't add all "apps" folder with partially fixed icons.
4. Are all icons in the application menu are white? I've pushed `libreoffice` icon so it should display with the right colour. If that is correct and other icons are white please see point 2. In the meantime You could override that buy changing general system colours manually in the Plasma settings (Plasma 5, I'm not in Plasma 6 yet), go `Appearances/Colours` and choose `edit colour scheme`. Find the w`indow text` colour and change it to `#ebdbb2`. Eventually You could [download](https://github.com/SylEleuth/dotfiles/blob/master/KDE/.local/share/color-scheme/GruvboxPlusDark.colors) and use my own scheme. If you prefer to not modify anything and stay with Your colour the only option is to wait until I finish modifying the apps icons.

**Comment by mercifulboss** [comment]
Thank you very much for taking the time!

1. Everything looks great! I especially like the new dolphin icon 😍. Spectacle also works and looks great!
2. The hybrid icon still doesn't seem to work:
![image](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/90151527/72387539-f9a8-4bf3-8a72-75712cdd2144)
3. Makes sense. Thanks alot for doing this.
4. Libreoffice works but the rest are white:
![gruvbox icons application menu partially updated](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/90151527/6cb677d3-d5f0-4ad8-83b0-ce3132339842)

Thanks, I was able to successfully change color schemes! I am not sure what to do with dotfiles so I didn't change that.

**Comment by SylEleuth** [comment]
I made (another) mistake and linked the wrong `dolphin` icon. The one You see is for `dolphin emulator` app. I fixed it. Probably it will be disappointing in comparison. But there is a different problem - why it displays 16px size icon and not full (scalable) one? Can You tell me what You see now? Can You look at the file in `/usr/share/applications/org.kde.dolphin.desktop` and give me the `icon=` name?

Color scheme folder is located in `~/.local/share/color-schemes` where You can copy the file.

Still don't know what is going on with `hybrid` icon. It will take more time to figure it out.

**Comment by mercifulboss** [comment]
Here is what I see after updating:
![image](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/90151527/9bcf705b-0478-4a88-9784-6a7865074c8a)

>/usr/share/applications/org.kde.dolphin.desktop

Going to this path only takes me back to the gruvbox-icon-plus folder since I made it as a symlink so I can `git pull`. I don't see any option for a `icon =`. Where should I look to find it?

>Color scheme folder is located in ~/.local/share/color-schemes where You can copy the file.

Thanks! I found it.

>Still don't know what is going on with hybrid icon. It will take more time to figure it out.

To me it sounds like the app overrides its icon, but i'm not sure. not an expert.

**Comment by SylEleuth** [comment]
Do not try to open that file straight from the path bar. Go to folder `/usr/share/applications` first and tell me if there is a file named `org.kde.dolphin.desktop`.
If You can't find it there, go to `~/.local/share/applications` next and check there.

**Comment by mercifulboss** [comment]
> Do not try to open that file straight from the path bar. Go to folder `/usr/share/applications` first and tell me if there is a file named `org.kde.dolphin.desktop`. If You can't find it there, go to `~/.local/share/applications` next and check there.

The folder is right there:

![image](https://github.com/SylEleuth/gruvbox-plus-icon-pack/assets/90151527/26399512-57d1-46ec-a8bb-fc2a516af392)

**Comment by SylEleuth** [comment]
I'm closing it for now. If You'll find something broken please open a new issue.

Thank You for the contribution.
